version: '3'

services:
  mediaDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5500:5432"

  redis-first-storage:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  redis-second-storage:
    image: redis/redis-stack-server:latest
    ports:
      - "6378:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

